owner: aydgn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aydoğan
    url: https://aydogan.dev
  - name: HDI Fiba Emeklilik İnternet Şube
    url: https://internetsube.hdifibaemeklilik.com.tr/
  - name: Robert College
    url: https://website.robcol.k12.tr/en/home-page
  - name: Bahçıvan Peynir
    url: https://www.bahcivanpeynir.com/
  - name: Casa Lavanda
    url: https://www.casalavanda.com.tr/
  - name: Çokyaşar Holding
    url: https://www.cokyasarholding.com.tr/
  - name: Digizoo
    url: https://www.digizoo.com.tr/
  - name: Elmas Yeşiloğlu
    url: https://www.elmasyesiloglu.com/
  - name: Erdem & Erdem
    url: https://www.erdem-erdem.av.tr/
  - name: Erdemir Özmen
    url: https://www.erdemirozmen.com/
  - name: Fiba Air
    url: https://www.fibaair.com.tr/
  - name: Fiba Faktoring
    url: https://www.fibafaktoring.com.tr/
  - name: Fiba Group
    url: https://www.fibagroup.com/
  - name: GIG
    url: https://www.gig.com.tr/
  - name: Hotel Partner
    url: https://www.hotelpartner.com.tr/
  - name: İş Faktoring
    url: https://www.isfaktoring.com.tr/
  - name: İzdemir Enerji
    url: https://www.izdemirenerji.com/
  - name: Kariabel
    url: https://www.kariabel.com/
  - name: Katılım Emeklilik
    url: https://www.katilimemeklilik.com.tr/
  - name: Maxis GS
    url: https://www.maxisgs.com/
  - name: Medistate
    url: https://www.medistate.com.tr/
  - name: Melodi
    url: https://www.melodi.com.tr/
  - name: Miilux
    url: https://www.miilux.com.tr/
  - name: Noas
    url: https://www.noas.com.tr/
  - name: Obase
    url: https://www.obase.com/
  - name: Özersoylar
    url: https://www.ozersoylar.com/
  - name: Özyasar
    url: https://www.ozyasar.com.tr/
  - name: Penta
    url: https://www.penta.com.tr/
  - name: Prefus
    url: https://www.prefus.com.tr/
  - name: Satem Grup
    url: https://www.satemgrup.com.tr/
  - name: Sompo Sigorta
    url: https://www.somposigorta.com.tr/
  - name: Tatmetal
    url: https://www.tatmetal.com/
  - name: TEB Faktoring
    url: https://www.tebfaktoring.com.tr/
  - name: Time PR
    url: https://www.timepr.com/
  - name: Tobbund
    url: https://www.tobbund.com.tr/
  - name: Tosyalı Holding
    url: https://www.tosyaliholding.com.tr/
  - name: TSKB
    url: https://www.tskb.com.tr/
  - name: TVF
    url: https://www.tvf.com.tr/
  - name: UBC Chemicals
    url: https://www.ubcchemicals.com/
  - name: Uno
    url: https://www.uno.com.tr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    # - title: Status
      # href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
